
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvdkihicwovcfbwlfmrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZGtpaGljd292Y2Zid2xmbXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzEwODYsImV4cCI6MjA2MzA0NzA4Nn0.ROGAjrT1ddd9j5XTEwhLROwy0R-FM7uoHItfsdyZciY";

// Create Supabase client with auth configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function to get the current session
export const getSession = async () => {
  const { data } = await supabase.auth.getSession();
  return data.session;
};

// Track activity
export const trackActivity = async (userId: string, activityType: string, description: string, entityId?: string) => {
  if (!userId) return;
  
  try {
    await supabase.from('user_activity').insert({
      user_id: userId,
      activity_type: activityType,
      description,
      entity_id: entityId
    });
  } catch (error) {
    console.error('Failed to track activity:', error);
  }
};
