// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvdkihicwovcfbwlfmrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZGtpaGljd292Y2Zid2xmbXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzEwODYsImV4cCI6MjA2MzA0NzA4Nn0.ROGAjrT1ddd9j5XTEwhLROwy0R-FM7uoHItfsdyZciY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);